### ISSUE TITLE
Scale

### ISSUE THREAD

**Issue by Tom-Neverwinter** [maduce/fosscad-repo#1]
When opening various files they are not properly sized and appear about 1mm in size. What is the appropriate scale? (not taking into account abs/pla shrinkage/expanditure)

**Comment by maduce** [comment]
You likely need to change the units from mm to inches in the program you are using for it to scale property. A lesser but alternative solution is to change the scale from 1 to 25.4 (1 inch to 25.4 mm).  Most of the designs are designed with inches in mind but it depends on the designer; some designers are in countries that use the metric system.  Often times software is set to the metric standard by default.

**Comment by Tom-Neverwinter** [comment]
For the longest time I could not figure it out. Thank you
