### ISSUE TITLE
G17 DIY Rail

### ISSUE THREAD

**Issue by akneipp** [maduce/fosscad-repo#21]
Left_Rail_Section_Drawing_v3.pdf, the left rail shows a 1.16mm dimension for the slide mating surface, the matching dimension on Right_Rail_Section_Drawing_v2.pdf only shows .16mm. I believe these two dims should match.

![Untitled](https://user-images.githubusercontent.com/15385484/58809829-a8106900-85ea-11e9-8246-6819fe44a402.png)

**Comment by maduce** [comment]
Yeah there shouldn’t be two versions of the rear rail files and the left and right should both be at V3. Working on getting this fixed in the parts folder.

**Comment by maduce** [comment]
Right_Rail_Section_Drawing_v2.pdf has been corrected and Left_Rail_Section_Drawing_v2.pdf  was removed because its an old spec sheet. 

Thanks akneipp!
