### ISSUE TITLE
Pistol>1911 45 magazine stl file is missing

### ISSUE THREAD

**Issue by hanoncs** [maduce/fosscad-repo#3]
I went to try and print the 191 magazine in the 4.8 pack and there is a weird stl file there, its not a printable magazine.

**Comment by maduce** [comment]
Did you try to export the magazine cad to stl from the provided STEP files? You can open the step files in freecad, solidworks, inventor, or many other cad programs.

**Comment by pechkin88** [comment]
The step file contains a frame, but not the magazine.  Is it possible to add all magazine parts? Thanks

**Comment by maduce** [comment]
Someone in IRC can probably help you get 1911 CAD which hasn't been released yet.
