### ISSUE TITLE
Scaling

### ISSUE THREAD

**Issue by hyudryu** [maduce/fosscad-repo#4]
The scale is wrong on these stl files, when I try to slice them it seems like they are like 4mm big lol

**Comment by mx201er** [comment]
It was probably exported in mm and you're importing it in inches. Just
scale it by 25.4x

**Comment by maduce** [comment]
Agreed, change the scale from mm to inches and it should scale to the correct size. You can also multiple the scale by 25.4 (1 in. = 25.4mm).
