### ISSUE TITLE
Pla or abs for bump stock 

### ISSUE THREAD

**Issue by coyotebush2384** [maduce/fosscad-repo#5]
Wondering if pla would hold up or does this need to be printed in abs

**Comment by BradGroux** [comment]
PLA works fine, just remember that it can shrink somewhat so you may need to adjust for that.

**Comment by jimilinuxguy** [comment]
What orientation are you guys printing?

**Comment by maduce** [comment]
We printed it in PLA except the stock pad part which was printed in ninjaflex. We printed it in several pieces and the orientation was in such a way that it would fit in the printer envelope. The rear stock piece was printed so the layers go vertical when you're using it...so it would've been laying butt end down on the bed. The grip part was printed laying flat against the place where it connects to the stock part.

![bumpfirestock3](https://user-images.githubusercontent.com/3700928/40090837-2596055c-5869-11e8-9887-98c474cff2a7.jpg)
