### ISSUE TITLE
Not correctly scaled

### ISSUE THREAD

**Issue by MatCat** [maduce/fosscad-repo#9]
I tried to use the STL's in Simplify3D and found that the parts are massively larger then they should be, the pins alone for example are 38mm diameter and 137mm tall.  Does anyone know the exact dimensions of the pin so I can rescale?

**Comment by maduce** [comment]
Try changing the units from inches to mm. that should scale it down if its to large. if you want to use scale try scaling down by a factor of 25.4 (1 inch = 25.4 millimeters) or 0.03937007874.
